#!/bin/sh

DIR=$(dirname ${BASH_SOURCE[0]})

case $BLOCK_BUTTON in
	1) notify-send -t 3000 "$(date '+%A')" " $(date '+%B %dXX' | sed -r -e 's/(1[123])XX/\1th/;s/1XX/1st/;s/2XX/2nd/;s/3XX/3rd/;s/XX/th/;s/ 0/ /')" & ;;
#	2) kitty --name "Calendar" -e bash -c "cal -y; read  -n 1 -p '' ignored" & ;;
    3) /home/trg/.config/dusk/scripts/statusbar/yad-cal.sh ;;
	4) notify-send -t 9000 "$(date '+%A')" "$(cal --color=never)" & ;;
	8) subl $DIR/clock ;;
	9) subl $DIR/clock_click ;;
	*) notify-send -t 2000 "clock $BLOCK_BUTTON" & ;;
esac


