#!/bin/bash

DIR=$(dirname ${BASH_SOURCE[0]})

case $BLOCK_BUTTON in
	1) archlinux-logout & ;;
	3) /home/trg/.config/dusk/scripts/menu/system & ;;
	8) subl $DIR/startbutton ;;
	9) subl $DIR/startbutton_click ;;
	*) notify-send -t 1000 "startbutton $BLOCK_BUTTON" & ;;

esac
